import { IHsv, IHsl, IColor, ICmy } from './interface';
export declare const hsl2hsv: ({ h, s, l }: IHsl) => IHsv;
export declare const hsv2hsl: ({ h, s, v }: IHsv) => IHsl;
export declare const rgb2hsv: ({ r, g, b }: IColor) => IHsv;
export declare const hsv2rgb: ({ h, s, v }: IHsv) => IColor;
export declare const hsl2rgb: ({ h, s, l }: IHsl) => IColor;
export declare const rgb2hsl: ({ r, g, b }: IColor) => IHsl;
export declare const cmy2rgb: (cyan: number, magenta: number, yellow: number) => ICmy;
export declare const rgb2cmy: ({ r, g, b }: IColor) => IColor;
export declare const rgba2rgbByMap: (rgba: IColor, bgMap?: IColor) => IColor;
export declare const rgba2rgb: (color: string, bgColor?: string) => IColor;
export declare const alpha2rgb: (color: string) => IColor;
export declare const convert: (color: string | IColor | IHsl | IHsv, target?: string) => string | IColor | IHsl | IHsv;
