declare const _default: {
    toRgb: (color: string) => string;
    toHex: (color: string) => string;
    toHsv: (color: string) => string;
    toHsl: (color: string) => string;
    toRgba: (color: string, alpha?: number | undefined) => string;
    toHexa: (color: string, alpha?: number | undefined) => string;
    toHsva: (color: string, alpha?: number | undefined) => string;
    toHsla: (color: string, alpha?: number | undefined) => string;
    isColor: (color: string, type?: string | undefined) => boolean;
    convert: (color: string | import("./interface").IColor | import("./interface").IHsl | import("./interface").IHsv, target?: string | undefined) => string | import("./interface").IColor | import("./interface").IHsl | import("./interface").IHsv;
    rgbaToRgb: (color: string, bgColor?: string | undefined) => string;
    darkColor: (color: string, criticalValue?: number) => boolean | undefined;
    lightColor: (color: string, criticalValue?: number) => boolean | undefined;
    getColorMap: (color: string) => import("./interface").IColor | import("./interface").IHsl | import("./interface").IHsv;
    formatColor: (color: string) => string;
    getColorDepth: (color: string) => number;
    version: string;
};
export default _default;
